D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCEA1GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCET1GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCET2GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCET3GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCWA1GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCWA2GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCWT1GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCWT2GW.exe
PAUSE
