D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCEM1GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCEM2GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCEM3GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCEM4GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCSM1GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCSM2GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCSM3GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCSM4GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCSM5GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCWM1GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCWM2GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCWM3GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCOS1GW.exe

D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCEA1GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCET1GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCET2GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCET3GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCWA1GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCWA2GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCWT1GW.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.PLCWT2GW.exe

D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.SortEngine.exe
D:\2PALS\SAC\InstallUtil.exe D:\2PALS\SAC\PALS.SvcMonitor.exe


PAUSE
